### ISSUE TITLE
Genius animation is failing to play when deployed to production.

### ISSUE THREAD

**Issue by bbeck** [bbeck/puzzles-with-chat#6]
I suspect it might have something to do with how the CSS is optimized by webpack.

```css
@-webkit-keyframes banner {
    0% {
        background-image: radial-gradient(#000,transparent,transparent);
        opacity: 1%;  /* <-- should be 100% */
        -webkit-transform: scale(0);
        transform: scale(0)
    }
```
